### ISSUE TITLE
Exclude localhost redirect

### ISSUE THREAD

**Issue by jetaix** [nuxt-contrib/redirect-ssl#29]
How can I avoid a redirect on my localhost in order to execute my e2e test in local without a ssl certificat ?

I'm trying some trick like: 
`redirectSSL.create({ exclude: ['localhost'] })`

**Comment by ricardogobbosouza** [comment]
Hi @jetaix 
You are doing it right!
The option `exclude` is for that :smile:

**Comment by ricardogobbosouza** [comment]
We will update the documentation if the user wanted to disable redirection on localhost.
