### ISSUE TITLE
How to use options in nuxt.config.js

### ISSUE THREAD

**Issue by drewbaker** [nuxt-contrib/redirect-ssl#32]
How do I use the options? I tried this in `nuxt.config.js`:

```
    serverMiddleware: [
        [
            "redirect-ssl",
            {
                redirect: process.env.SSL_REDIRECT_ENABLED === "true"
            }
        ]
    ],
```

But I get error ` ServerMiddleware should expose a handle: undefined `.

**Comment by pi0** [comment]
Hi. Sorry for late response. I've updated nuxt.js section: https://github.com/nuxt-contrib/redirect-ssl#using-with-nuxtjs (please notice package version is bumped to 2)
